
var ZD = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(ZD) {
  ZD = ZD || {};


var a;a||(a=typeof ZD !== 'undefined' ? ZD : {});
var Promise=function(){function c(){}function f(b,d){return function(){b.apply(d,arguments)}}function e(b){if(!(this instanceof e))throw new TypeError("Promises must be constructed via new");if("function"!==typeof b)throw new TypeError("not a function");this.s=0;this.B=!1;this.u=void 0;this.v=[];A(b,this)}function n(b,d){for(;3===b.s;)b=b.u;0===b.s?b.v.push(d):(b.B=!0,e.C(function(){var g=1===b.s?d.F:d.G;if(null===g)(1===b.s?l:p)(d.A,b.u);else{try{var h=g(b.u)}catch(k){p(d.A,k);return}l(d.A,h)}}))}
function l(b,d){try{if(d===b)throw new TypeError("A promise cannot be resolved with itself.");if(d&&("object"===typeof d||"function"===typeof d)){var g=d.then;if(d instanceof e){b.s=3;b.u=d;w(b);return}if("function"===typeof g){A(f(g,d),b);return}}b.s=1;b.u=d;w(b)}catch(h){p(b,h)}}function p(b,d){b.s=2;b.u=d;w(b)}function w(b){2===b.s&&0===b.v.length&&e.C(function(){b.B||e.H(b.u)});for(var d=0,g=b.v.length;d<g;d++)n(b,b.v[d]);b.v=null}function q(b,d,g){this.F="function"===typeof b?b:null;this.G="function"===
typeof d?d:null;this.A=g}function A(b,d){var g=!1;try{b(function(h){g||(g=!0,l(d,h))},function(h){g||(g=!0,p(d,h))})}catch(h){g||(g=!0,p(d,h))}}e.prototype["catch"]=function(b){return this.then(null,b)};e.prototype.then=function(b,d){var g=new this.constructor(c);n(this,new q(b,d,g));return g};e.C="function"===typeof setImmediate&&function(b){setImmediate(b)}||function(b){setTimeout(b,0)};e.H=function(b){"undefined"!==typeof console&&console&&console.warn("Possible Unhandled Promise Rejection:",b)};
return e}(),r,t;a.ready=new Promise(function(c,f){r=c;t=f});var u={},x;for(x in a)a.hasOwnProperty(x)&&(u[x]=a[x]);var y="";document.currentScript&&(y=document.currentScript.src);_scriptDir&&(y=_scriptDir);0!==y.indexOf("blob:")?y=y.substr(0,y.lastIndexOf("/")+1):y="";var z=a.printErr||console.warn.bind(console);for(x in u)u.hasOwnProperty(x)&&(a[x]=u[x]);u=null;var B;a.wasmBinary&&(B=a.wasmBinary);var noExitRuntime;a.noExitRuntime&&(noExitRuntime=a.noExitRuntime);"object"!==typeof WebAssembly&&C("no native wasm support detected");
var D,E=new WebAssembly.Table({initial:1,maximum:1,element:"anyfunc"}),F=!1;function G(c){var f=a["_"+c];f||C("Assertion failed: Cannot call unknown function "+(c+", make sure it is exported"));return f}
function aa(c,f,e,n){var l={string:function(b){var d=0;if(null!==b&&void 0!==b&&0!==b){var g=(b.length<<2)+1;d=H(g);var h=d,k=I;if(0<g){g=h+g-1;for(var v=0;v<b.length;++v){var m=b.charCodeAt(v);if(55296<=m&&57343>=m){var ha=b.charCodeAt(++v);m=65536+((m&1023)<<10)|ha&1023}if(127>=m){if(h>=g)break;k[h++]=m}else{if(2047>=m){if(h+1>=g)break;k[h++]=192|m>>6}else{if(65535>=m){if(h+2>=g)break;k[h++]=224|m>>12}else{if(h+3>=g)break;k[h++]=240|m>>18;k[h++]=128|m>>12&63}k[h++]=128|m>>6&63}k[h++]=128|m&63}}k[h]=
0}}return d},array:function(b){var d=H(b.length);J.set(b,d);return d}},p=G(c),w=[];c=0;if(n)for(var q=0;q<n.length;q++){var A=l[e[q]];A?(0===c&&(c=K()),w[q]=A(n[q])):w[q]=n[q]}e=p.apply(null,w);e=function(b){if("string"===f)if(b){for(var d=I,g=b+NaN,h=b;d[h]&&!(h>=g);)++h;if(16<h-b&&d.subarray&&L)b=L.decode(d.subarray(b,h));else{for(g="";b<h;){var k=d[b++];if(k&128){var v=d[b++]&63;if(192==(k&224))g+=String.fromCharCode((k&31)<<6|v);else{var m=d[b++]&63;k=224==(k&240)?(k&15)<<12|v<<6|m:(k&7)<<18|
v<<12|m<<6|d[b++]&63;65536>k?g+=String.fromCharCode(k):(k-=65536,g+=String.fromCharCode(55296|k>>10,56320|k&1023))}}else g+=String.fromCharCode(k)}b=g}}else b="";else b="boolean"===f?!!b:b;return b}(e);0!==c&&M(c);return e}var L="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0,N,J,I,O=a.INITIAL_MEMORY||140247040;a.wasmMemory?D=a.wasmMemory:D=new WebAssembly.Memory({initial:O/65536,maximum:O/65536});D&&(N=D.buffer);O=N.byteLength;var P=N;N=P;a.HEAP8=J=new Int8Array(P);a.HEAP16=new Int16Array(P);
a.HEAP32=new Int32Array(P);a.HEAPU8=I=new Uint8Array(P);a.HEAPU16=new Uint16Array(P);a.HEAPU32=new Uint32Array(P);a.HEAPF32=new Float32Array(P);a.HEAPF64=new Float64Array(P);var Q=[],R=[],ba=[],S=[];function ca(){var c=a.preRun.shift();Q.unshift(c)}Math.imul&&-5===Math.imul(4294967295,5)||(Math.imul=function(c,f){var e=c&65535,n=f&65535;return e*n+((c>>>16)*n+e*(f>>>16)<<16)|0});if(!Math.fround){var da=new Float32Array(1);Math.fround=function(c){da[0]=c;return da[0]}}
Math.clz32||(Math.clz32=function(c){var f=32,e=c>>16;e&&(f-=16,c=e);if(e=c>>8)f-=8,c=e;if(e=c>>4)f-=4,c=e;if(e=c>>2)f-=2,c=e;return c>>1?f-2:f-c});Math.trunc||(Math.trunc=function(c){return 0>c?Math.ceil(c):Math.floor(c)});var T=0,U=null,V=null;a.preloadedImages={};a.preloadedAudios={};function C(c){if(a.onAbort)a.onAbort(c);z(c);F=!0;c=new WebAssembly.RuntimeError("abort("+c+"). Build with -s ASSERTIONS=1 for more info.");t(c);throw c;}
function ea(){var c=W;return String.prototype.startsWith?c.startsWith("data:application/octet-stream;base64,"):0===c.indexOf("data:application/octet-stream;base64,")}var W="zstddec.wasm";if(!ea()){var fa=W;W=a.locateFile?a.locateFile(fa,y):y+fa}function ia(){try{if(B)return new Uint8Array(B);throw"both async and sync fetching of the wasm failed";}catch(c){C(c)}}
function ja(){return B||"function"!==typeof fetch?Promise.resolve().then(ia):fetch(W,{credentials:"same-origin"}).then(function(c){if(!c.ok)throw"failed to load wasm binary file at '"+W+"'";return c.arrayBuffer()}).catch(function(){return ia()})}function X(c){for(;0<c.length;){var f=c.shift();if("function"==typeof f)f(a);else{var e=f.D;"number"===typeof e?void 0===f.w?E.get(e)():E.get(e)(f.w):e(void 0===f.w?null:f.w)}}}
var ka=Uint8Array.prototype.copyWithin?function(c,f,e){I.copyWithin(c,f,f+e)}:function(c,f,e){I.set(I.subarray(f,f+e),c)};R.push({D:function(){la()}});var ma={b:E,c:ka,d:function(){C("OOM")},a:D};
(function(){function c(l){a.asm=l.exports;T--;a.monitorRunDependencies&&a.monitorRunDependencies(T);0==T&&(null!==U&&(clearInterval(U),U=null),V&&(l=V,V=null,l()))}function f(l){c(l.instance)}function e(l){return ja().then(function(p){return WebAssembly.instantiate(p,n)}).then(l,function(p){z("failed to asynchronously prepare wasm: "+p);C(p)})}var n={a:ma};T++;a.monitorRunDependencies&&a.monitorRunDependencies(T);if(a.instantiateWasm)try{return a.instantiateWasm(n,c)}catch(l){return z("Module.instantiateWasm callback failed with error: "+
l),!1}(function(){if(B||"function"!==typeof WebAssembly.instantiateStreaming||ea()||"function"!==typeof fetch)return e(f);fetch(W,{credentials:"same-origin"}).then(function(l){return WebAssembly.instantiateStreaming(l,n).then(f,function(p){z("wasm streaming compile failed: "+p);z("falling back to ArrayBuffer instantiation");return e(f)})})})();return{}})();var la=a.___wasm_call_ctors=function(){return(la=a.___wasm_call_ctors=a.asm.e).apply(null,arguments)};
a._malloc=function(){return(a._malloc=a.asm.f).apply(null,arguments)};a._free=function(){return(a._free=a.asm.g).apply(null,arguments)};a._ZSTD_isError=function(){return(a._ZSTD_isError=a.asm.h).apply(null,arguments)};a._ZSTD_getErrorName=function(){return(a._ZSTD_getErrorName=a.asm.i).apply(null,arguments)};a._ZSTD_createDStream=function(){return(a._ZSTD_createDStream=a.asm.j).apply(null,arguments)};a._ZSTD_freeDStream=function(){return(a._ZSTD_freeDStream=a.asm.k).apply(null,arguments)};
a._ZSTD_DStreamInSize=function(){return(a._ZSTD_DStreamInSize=a.asm.l).apply(null,arguments)};a._ZSTD_DStreamOutSize=function(){return(a._ZSTD_DStreamOutSize=a.asm.m).apply(null,arguments)};a._ZSTD_initDStream=function(){return(a._ZSTD_initDStream=a.asm.n).apply(null,arguments)};a._ZSTD_decompressStream=function(){return(a._ZSTD_decompressStream=a.asm.o).apply(null,arguments)};
var K=a.stackSave=function(){return(K=a.stackSave=a.asm.p).apply(null,arguments)},M=a.stackRestore=function(){return(M=a.stackRestore=a.asm.q).apply(null,arguments)},H=a.stackAlloc=function(){return(H=a.stackAlloc=a.asm.r).apply(null,arguments)};a.cwrap=function(c,f,e,n){e=e||[];var l=e.every(function(p){return"number"===p});return"string"!==f&&l&&!n?G(c):function(){return aa(c,f,e,arguments)}};var Y;V=function na(){Y||Z();Y||(V=na)};
function Z(){function c(){if(!Y&&(Y=!0,a.calledRun=!0,!F)){X(R);X(ba);r(a);if(a.onRuntimeInitialized)a.onRuntimeInitialized();if(a.postRun)for("function"==typeof a.postRun&&(a.postRun=[a.postRun]);a.postRun.length;){var f=a.postRun.shift();S.unshift(f)}X(S)}}if(!(0<T)){if(a.preRun)for("function"==typeof a.preRun&&(a.preRun=[a.preRun]);a.preRun.length;)ca();X(Q);0<T||(a.setStatus?(a.setStatus("Running..."),setTimeout(function(){setTimeout(function(){a.setStatus("")},1);c()},1)):c())}}a.run=Z;
if(a.preInit)for("function"==typeof a.preInit&&(a.preInit=[a.preInit]);0<a.preInit.length;)a.preInit.pop()();noExitRuntime=!0;Z();


  return ZD.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
      module.exports = ZD;
    else if (typeof define === 'function' && define['amd'])
      define([], function() { return ZD; });
    else if (typeof exports === 'object')
      exports["ZD"] = ZD;
    