
var a;a||(a=typeof Module !== 'undefined' ? Module : {});var e={},g;for(g in a)a.hasOwnProperty(g)&&(e[g]=a[g]);var h="";"undefined"!==typeof document&&document.currentScript&&(h=document.currentScript.src);h=0!==h.indexOf("blob:")?h.substr(0,h.lastIndexOf("/")+1):"";var k=a.printErr||console.warn.bind(console);for(g in e)e.hasOwnProperty(g)&&(a[g]=e[g]);e=null;var m;a.wasmBinary&&(m=a.wasmBinary);var noExitRuntime=a.noExitRuntime||!0;"object"!==typeof WebAssembly&&n("no native wasm support detected");
var p,q=!1,r,t,u=[],v=[],w=[];function y(){var b=a.preRun.shift();u.unshift(b)}var z=0,A=null,B=null;a.preloadedImages={};a.preloadedAudios={};function n(b){if(a.onAbort)a.onAbort(b);k(b);q=!0;throw new WebAssembly.RuntimeError("abort("+b+"). Build with -s ASSERTIONS=1 for more info.");}function C(){return D.startsWith("data:application/octet-stream;base64,")}var D;D="xzdec-wasm.wasm";if(!C()){var E=D;D=a.locateFile?a.locateFile(E,h):h+E}
function F(){var b=D;try{if(b==D&&m)return new Uint8Array(m);throw"both async and sync fetching of the wasm failed";}catch(d){n(d)}}function G(){return m||"function"!==typeof fetch?Promise.resolve().then(function(){return F()}):fetch(D,{credentials:"same-origin"}).then(function(b){if(!b.ok)throw"failed to load wasm binary file at '"+D+"'";return b.arrayBuffer()}).catch(function(){return F()})}
function H(b){for(;0<b.length;){var d=b.shift();if("function"==typeof d)d(a);else{var f=d.u;"number"===typeof f?void 0===d.s?t.get(f)():t.get(f)(d.s):f(void 0===d.s?null:d.s)}}}var I={a:function(b,d,f){r.copyWithin(b,d,d+f)},b:function(){n("OOM")}};
(function(){function b(c){a.asm=c.exports;p=a.asm.c;c=p.buffer;a.HEAP8=new Int8Array(c);a.HEAP16=new Int16Array(c);a.HEAP32=new Int32Array(c);a.HEAPU8=r=new Uint8Array(c);a.HEAPU16=new Uint16Array(c);a.HEAPU32=new Uint32Array(c);a.HEAPF32=new Float32Array(c);a.HEAPF64=new Float64Array(c);t=a.asm.o;v.unshift(a.asm.d);z--;a.monitorRunDependencies&&a.monitorRunDependencies(z);0==z&&(null!==A&&(clearInterval(A),A=null),B&&(c=B,B=null,c()))}function d(c){b(c.instance)}function f(c){return G().then(function(l){return WebAssembly.instantiate(l,
x)}).then(c,function(l){k("failed to asynchronously prepare wasm: "+l);n(l)})}var x={a:I};z++;a.monitorRunDependencies&&a.monitorRunDependencies(z);if(a.instantiateWasm)try{return a.instantiateWasm(x,b)}catch(c){return k("Module.instantiateWasm callback failed with error: "+c),!1}(function(){return m||"function"!==typeof WebAssembly.instantiateStreaming||C()||"function"!==typeof fetch?f(d):fetch(D,{credentials:"same-origin"}).then(function(c){return WebAssembly.instantiateStreaming(c,x).then(d,function(l){k("wasm streaming compile failed: "+
l);k("falling back to ArrayBuffer instantiation");return f(d)})})})();return{}})();a.___wasm_call_ctors=function(){return(a.___wasm_call_ctors=a.asm.d).apply(null,arguments)};a._init=function(){return(a._init=a.asm.e).apply(null,arguments)};a._init_decompression=function(){return(a._init_decompression=a.asm.f).apply(null,arguments)};a._input_empty=function(){return(a._input_empty=a.asm.g).apply(null,arguments)};a._get_in_buffer=function(){return(a._get_in_buffer=a.asm.h).apply(null,arguments)};
a._set_new_input=function(){return(a._set_new_input=a.asm.i).apply(null,arguments)};a._decompress=function(){return(a._decompress=a.asm.j).apply(null,arguments)};a._get_out_pos=function(){return(a._get_out_pos=a.asm.k).apply(null,arguments)};a._get_out_buffer=function(){return(a._get_out_buffer=a.asm.l).apply(null,arguments)};a._out_buffer_cleared=function(){return(a._out_buffer_cleared=a.asm.m).apply(null,arguments)};a._release=function(){return(a._release=a.asm.n).apply(null,arguments)};var J;
B=function K(){J||L();J||(B=K)};
function L(){function b(){if(!J&&(J=!0,a.calledRun=!0,!q)){H(v);if(a.onRuntimeInitialized)a.onRuntimeInitialized();if(a.postRun)for("function"==typeof a.postRun&&(a.postRun=[a.postRun]);a.postRun.length;){var d=a.postRun.shift();w.unshift(d)}H(w)}}if(!(0<z)){if(a.preRun)for("function"==typeof a.preRun&&(a.preRun=[a.preRun]);a.preRun.length;)y();H(u);0<z||(a.setStatus?(a.setStatus("Running..."),setTimeout(function(){setTimeout(function(){a.setStatus("")},1);b()},1)):b())}}a.run=L;
if(a.preInit)for("function"==typeof a.preInit&&(a.preInit=[a.preInit]);0<a.preInit.length;)a.preInit.pop()();L();
