// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

/* global describe, it, beforeEach, afterEach */

describe('Clicking around', function () {
    this.timeout(30000)
    let driver
    let vars
    beforeEach(async function () {
        driver = await new Builder().forBrowser('firefox').build()
        vars = {}
    })
    afterEach(async function () {
        await driver.quit();
    })
    it('Clicking around', async function () {
        await driver.get('http://localhost:8080/dist/www/index.html')
        await driver.manage().window().setRect({ width: 550, height: 692 })
        await driver.findElement(By.id('archiveFiles')).click()
        await driver.findElement(By.id('archiveFiles')).sendKeys('C:\\fakepath\\wikipedia_en_ray_charles_2015-06.zimaa')
        await driver.findElement(By.id('prefix')).sendKeys('ray')
        await driver.switchTo().frame(0)
        await driver.findElement(By.id('mwZA')).click()
        await driver.switchTo().defaultContent()
        await driver.findElement(By.css('.fa-random > path')).click()
    })
})
