
var ZD = (() => {
  var _scriptDir = import.meta.url;
  
  return (
function(ZD = {})  {

var a;a||(a=typeof ZD !== 'undefined' ? ZD : {});var n,q;a.ready=new Promise((b,e)=>{n=b;q=e});var r=Object.assign({},a),v="";"undefined"!=typeof document&&document.currentScript&&(v=document.currentScript.src);_scriptDir&&(v=_scriptDir);0!==v.indexOf("blob:")?v=v.substr(0,v.replace(/[?#].*/,"").lastIndexOf("/")+1):v="";var w=a.printErr||console.warn.bind(console);Object.assign(a,r);r=null;var x;a.wasmBinary&&(x=a.wasmBinary);var noExitRuntime=a.noExitRuntime||!0;
"object"!=typeof WebAssembly&&z("no native wasm support detected");var A,B=!1,D,E,F=[],G=[],H=[];function I(){var b=a.preRun.shift();F.unshift(b)}var J=0,K=null,L=null;function z(b){if(a.onAbort)a.onAbort(b);b="Aborted("+b+")";w(b);B=!0;b=new WebAssembly.RuntimeError(b+". Build with -sASSERTIONS for more info.");q(b);throw b;}function M(b){return b.startsWith("data:application/octet-stream;base64,")}var N;
if(a.locateFile){if(N="zstddec-wasm.wasm",!M(N)){var O=N;N=a.locateFile?a.locateFile(O,v):v+O}}else N=(new URL("zstddec-wasm.wasm",import.meta.url)).href;function P(b){try{if(b==N&&x)return new Uint8Array(x);throw"both async and sync fetching of the wasm failed";}catch(e){z(e)}}
function Q(b){return x||"function"!=typeof fetch?Promise.resolve().then(()=>P(b)):fetch(b,{credentials:"same-origin"}).then(e=>{if(!e.ok)throw"failed to load wasm binary file at '"+b+"'";return e.arrayBuffer()}).catch(()=>P(b))}function R(b,e,d){return Q(b).then(f=>WebAssembly.instantiate(f,e)).then(f=>f).then(d,f=>{w("failed to asynchronously prepare wasm: "+f);z(f)})}
function aa(b,e){var d=N;return x||"function"!=typeof WebAssembly.instantiateStreaming||M(d)||"function"!=typeof fetch?R(d,b,e):fetch(d,{credentials:"same-origin"}).then(f=>WebAssembly.instantiateStreaming(f,b).then(e,function(y){w("wasm streaming compile failed: "+y);w("falling back to ArrayBuffer instantiation");return R(d,b,e)}))}function S(b){for(;0<b.length;)b.shift()(a)}var T="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ba(b,e,d,f){var y={string:c=>{var l=0;if(null!==c&&void 0!==c&&0!==c){for(var g=l=0;g<c.length;++g){var k=c.charCodeAt(g);127>=k?l++:2047>=k?l+=2:55296<=k&&57343>=k?(l+=4,++g):l+=3}var h=l+1;g=l=V(h);k=E;if(0<h){h=g+h-1;for(var p=0;p<c.length;++p){var m=c.charCodeAt(p);if(55296<=m&&57343>=m){var ca=c.charCodeAt(++p);m=65536+((m&1023)<<10)|ca&1023}if(127>=m){if(g>=h)break;k[g++]=m}else{if(2047>=m){if(g+1>=h)break;k[g++]=192|m>>6}else{if(65535>=m){if(g+2>=h)break;k[g++]=224|m>>12}else{if(g+
3>=h)break;k[g++]=240|m>>18;k[g++]=128|m>>12&63}k[g++]=128|m>>6&63}k[g++]=128|m&63}}k[g]=0}}return l},array:c=>{var l=V(c.length);D.set(c,l);return l}};b=a["_"+b];var u=[],C=0;if(f)for(var t=0;t<f.length;t++){var U=y[d[t]];U?(0===C&&(C=W()),u[t]=U(f[t])):u[t]=f[t]}d=b.apply(null,u);return d=function(c){0!==C&&X(C);if("string"===e)if(c){for(var l=E,g=c+NaN,k=c;l[k]&&!(k>=g);)++k;if(16<k-c&&l.buffer&&T)c=T.decode(l.subarray(c,k));else{for(g="";c<k;){var h=l[c++];if(h&128){var p=l[c++]&63;if(192==(h&
224))g+=String.fromCharCode((h&31)<<6|p);else{var m=l[c++]&63;h=224==(h&240)?(h&15)<<12|p<<6|m:(h&7)<<18|p<<12|m<<6|l[c++]&63;65536>h?g+=String.fromCharCode(h):(h-=65536,g+=String.fromCharCode(55296|h>>10,56320|h&1023))}}else g+=String.fromCharCode(h)}c=g}}else c="";else c="boolean"===e?!!c:c;return c}(d)}var da={b:function(b,e,d){E.copyWithin(b,e,e+d)},a:function(){z("OOM")}};
(function(){function b(d){d=d.exports;a.asm=d;A=a.asm.c;var f=A.buffer;a.HEAP8=D=new Int8Array(f);a.HEAP16=new Int16Array(f);a.HEAP32=new Int32Array(f);a.HEAPU8=E=new Uint8Array(f);a.HEAPU16=new Uint16Array(f);a.HEAPU32=new Uint32Array(f);a.HEAPF32=new Float32Array(f);a.HEAPF64=new Float64Array(f);G.unshift(a.asm.d);J--;a.monitorRunDependencies&&a.monitorRunDependencies(J);0==J&&(null!==K&&(clearInterval(K),K=null),L&&(f=L,L=null,f()));return d}var e={a:da};J++;a.monitorRunDependencies&&a.monitorRunDependencies(J);
if(a.instantiateWasm)try{return a.instantiateWasm(e,b)}catch(d){w("Module.instantiateWasm callback failed with error: "+d),q(d)}aa(e,function(d){b(d.instance)}).catch(q);return{}})();a._malloc=function(){return(a._malloc=a.asm.e).apply(null,arguments)};a._free=function(){return(a._free=a.asm.f).apply(null,arguments)};a._ZSTD_isError=function(){return(a._ZSTD_isError=a.asm.g).apply(null,arguments)};a._ZSTD_getErrorName=function(){return(a._ZSTD_getErrorName=a.asm.h).apply(null,arguments)};
a._ZSTD_createDStream=function(){return(a._ZSTD_createDStream=a.asm.i).apply(null,arguments)};a._ZSTD_freeDStream=function(){return(a._ZSTD_freeDStream=a.asm.j).apply(null,arguments)};a._ZSTD_DStreamInSize=function(){return(a._ZSTD_DStreamInSize=a.asm.k).apply(null,arguments)};a._ZSTD_DStreamOutSize=function(){return(a._ZSTD_DStreamOutSize=a.asm.l).apply(null,arguments)};a._ZSTD_initDStream=function(){return(a._ZSTD_initDStream=a.asm.m).apply(null,arguments)};
a._ZSTD_decompressStream=function(){return(a._ZSTD_decompressStream=a.asm.n).apply(null,arguments)};function W(){return(W=a.asm.p).apply(null,arguments)}function X(){return(X=a.asm.q).apply(null,arguments)}function V(){return(V=a.asm.r).apply(null,arguments)}a.cwrap=function(b,e,d,f){var y=!d||d.every(u=>"number"===u||"boolean"===u);return"string"!==e&&y&&!f?a["_"+b]:function(){return ba(b,e,d,arguments)}};var Y;L=function ea(){Y||Z();Y||(L=ea)};
function Z(){function b(){if(!Y&&(Y=!0,a.calledRun=!0,!B)){S(G);n(a);if(a.onRuntimeInitialized)a.onRuntimeInitialized();if(a.postRun)for("function"==typeof a.postRun&&(a.postRun=[a.postRun]);a.postRun.length;){var e=a.postRun.shift();H.unshift(e)}S(H)}}if(!(0<J)){if(a.preRun)for("function"==typeof a.preRun&&(a.preRun=[a.preRun]);a.preRun.length;)I();S(F);0<J||(a.setStatus?(a.setStatus("Running..."),setTimeout(function(){setTimeout(function(){a.setStatus("")},1);b()},1)):b())}}
if(a.preInit)for("function"==typeof a.preInit&&(a.preInit=[a.preInit]);0<a.preInit.length;)a.preInit.pop()();Z();


  return ZD.ready
}

);
})();
export default ZD;