FROM nginx:latest

EXPOSE 80

COPY ./manifest.json /usr/share/nginx/html/latest
COPY ./service-worker.js /usr/share/nginx/html/latest
COPY index.html /usr/share/nginx/html/latest
COPY CHANGELOG.md /usr/share/nginx/html/latest
COPY LICENSE-GPLv3.txt /usr/share/nginx/html/latest
COPY www /usr/share/nginx/html/www/latest